FROM nvcr.io/nvidia/tensorrt:20.12-py3

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH

RUN apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates \
    libglib2.0-0 libxext6 libsm6 libxrender1 \
    git mercurial subversion

RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

RUN apt-get install -y curl grep sed dpkg && \
    TINI_VERSION=`curl https://github.com/krallin/tini/releases/latest | grep -o "/v.*\"" | sed 's:^..\(.*\).$:\1:'` && \
    curl -L "https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini_${TINI_VERSION}.deb" > tini.deb && \
    dpkg -i tini.deb && \
    rm tini.deb && \
    apt-get clean

WORKDIR /
RUN apt-get update && apt-get -yq install python3-pil
RUN pip3 install jupyterlab torch torchvision fastai
RUN pip3 install ipywidgets && jupyter nbextension enable --py widgetsnbextension 
RUN echo "alias ls='ls --color=auto'" >> /root/.bashrc
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install curl git cmake ack g++ tmux -yq
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/qooba/vim-python-ide/master/setup.sh)" && echo "ok"
COPY jupyter /root/.jupyter

RUN git clone https://github.com/fastai/fastai
RUN pip3 install -e "fastai[dev]"

RUN git clone https://github.com/fastai/fastai1
RUN pip3 install -e "fastai1[dev]"

RUN pip3 install qdi fastapi uvicorn jinja2 aiofiles python-multipart
ENV PYTHONPATH="/app:${PYTHONPATH}"
WORKDIR /app

ENTRYPOINT [ "/usr/bin/tini", "--" ]
